### PR TITLE
DayZ Epoch 1.0.6 updates

### PR DESCRIPTION
**Pull request by ebayShopper**

### CODE REVIEW

**Comment by looonytoonz** [comment]
I seem to be having an issue with the "NATO Weapons Cache" - SM1 from the major missions...
the only NATO ammo that is spawning is the: DZ_AmmoBoxUS of which I assume are supposed to hold the: "2000Rnd_762x51_M134" ammo, and it is spawning on the outside of the crate. I do get the gear icon as if I can pick it up however upon clicking "G" it does not show up in the list allowing to pull it into your inventory....

**Comment by ebayShopper** [comment]
`2000Rnd_762x51_M134` is not added to any crates in DZMS. If you are manually adding it then those crates probably don't have enough room to hold it. You will have to add it to a different crate type.

**Comment by looonytoonz** [comment]
I did not change anything.... I do however have wai missions installed along side this. I remember seeing something about it pulling stuff from wia although I am unsure what and was wondering if it had anything to do with the chaingun ammo mission from that mission system. I was just noticing that the ammo box's on the ground look like the "2000Rnd_762x51_M134" ammo box's, but cannot be picked up even though they show a gear icon when looking at them. They spawn around the outside of the crate. Again these files are unedited. If I see it pop up while I am paying attention tonight I will record and upload a video of it to my youtube channel. Sorry for the late reply I was at work.

**Comment by looonytoonz** [comment]
Correction.... I just completed the mission again and this time there was ammo inside the box's that were spawned. not sure why there was no ammo in them previously, but seems to be working now.

**Comment by SMVampire** [comment]
Does this change compatibility with the base DayZ Mod? Otherwise the changes look great.

**Comment by ebayShopper** [comment]
All the changes I made are compatible with the latest vanilla DayZ mod too. However, DZMS has already been incompatible with vanilla for a while, since they banned all ammo crate types in the configs. The only crate that still works is `"AmmoBoxBig"`.

**Comment by SMVampire** [comment]
I wasn't aware. I'll merge your pull tonight.

Would you like to just be added as a collaborator on the main repo?

**Comment by ebayShopper** [comment]
If you want go ahead. I probably won't push anything else unless there are more compatibility issues that pop up in Epoch 1.0.6.2, vanilla 1.8.9 or the upcoming A2OA corepatch.

**Comment by SMVampire** [comment]
I added you. I'll let you decide the best way to merge the new updates and i'll update the official thread on EpochMod.com when you're finished.

**Pull request merged**
